FROM php:8.2-fpm-alpine

RUN apk add --no-cache --virtual .build-deps \
        autoconf \
        gcc \
        g++ \
        make \
        libtool \
        linux-headers \
        openssl-dev \
        && pecl install redis \
        && docker-php-ext-enable redis \
        && apk del .build-deps

COPY inc.php /var/www/html/inc.php
COPY php.ini /usr/local/etc/php/php.ini
COPY fpm.conf /usr/local/etc/php-fpm.d/z-performance.conf

RUN chown -R www-data:www-data /var/www/html