version: "3.8"

services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "no"]
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    network_mode: host

  app1:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "php swoole-server.php >> /var/log/server.log 2>&1"
    #stdin_open: true
    #tty: true
    environment:
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
      REDIS_DB: 0
    volumes:
      - ./logs:/var/log
    network_mode: host

#  app2:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: sh -c "php swoole-server.php >> /var/log/server.log 2>&1"
#    environment:
#      REDIS_HOST: 127.0.0.1
#      REDIS_PORT: 6379
#      REDIS_DB: 0
#    volumes:
#      - ./logs:/var/log
#    network_mode: host

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/host-mode.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs/nginx:/var/log/nginx
    ports: []
    network_mode: host

  fpm:
    build:
      context: .
      dockerfile: Dockerfile.fpm
    environment:
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
    ports: []
    network_mode: host

volumes:
  redis-data: