version: "3.8"

services:
  # ────────────────────────────────
  # Redis с персистентным хранением
  # ────────────────────────────────
  redis:
    image: redis:7-alpine
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - app-net

  # ────────────────────────────────
  # Приложение на Swoole + Slim
  # ────────────────────────────────
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    command: php swoole-server.php
    #command: ["sh"]
    stdin_open: true #tmp
    tty: true #tmp
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
    depends_on:
      - redis
    ports:
      - "9501:9501"
    networks:
      - app-net

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    command: php swoole-server.php
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
    depends_on:
      - redis
    ports:
      - "9502:9502"
    networks:
      - app-net

  # ────────────────────────────────
  # Nginx в роли фронтенд-балансировщика
  # ────────────────────────────────
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - app1
      - app2
    networks:
      - app-net

volumes:
  redis-data:

networks:
  app-net:
    driver: bridge